apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherapi
  name: weatherapi
  namespace: weatherapi
spec:
  ports:
  - nodePort: 31223
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weatherapi
  type: NodePort
